<?php

declare(strict_types=1);

$categories = [
    'Access and safe operations',
    'Preview and cleanup',
    'Analytics and diagnostics',
    'Export and masking',
    'Saved filters',
    'Testing and fixtures',
    'Release and packaging',
    'Performance and scalability',
    'Hardware planning',
    'Research and planning',
];

$focusAreas = [
    'admin guard coverage',
    'route input checks',
    'read-only preview paths',
    'write confirmation text',
    'stable error responses',
    'shared helper design',
    'operation limits',
    'fallback behavior',
    'acceptance checks',
    'fixture coverage',
    'result summaries',
    'dashboard visibility',
    'large-log behavior',
    'package validation',
    'release readiness',
    'local capacity reporting',
    'tool availability reporting',
    'manual rollout notes',
    'small-patch planning',
    'helper-first prototypes',
    'status tracking',
    'dependency mapping',
    'priority scoring',
    'review readiness',
    'next safe slice',
];

echo "# Generated 250 improvement backlog\n\n";
echo "This file is generated by tools/generate-improvement-backlog.php. It is a planning aid only.\n\n";

$count = 0;
foreach ($categories as $category) {
    echo "## {$category}\n\n";
    foreach ($focusAreas as $focus) {
        $count++;
        echo $count . '. Improve ' . $focus . ' for ' . strtolower($category) . ".\n";
    }
    echo "\n";
}

if ($count !== 250) {
    fwrite(STDERR, "Expected 250 improvements, generated {$count}.\n");
    exit(1);
}
